### PR TITLE
added method to get colors from a TiBlob

### PR DESCRIPTION
**Pull request by ludolphus**
Usage:

var image = Ti.UI.createImageView({image: ‘path_to_image’});
var colors = TiColorArt.analyzeImage(image.toImage());

### CODE REVIEW

**Comment by dezinezync** [comment]
Hey @ludolphus, thanks for this. Just a quick question, did you account for the changes from #2 ? Seems like you have, but just want to be sure.

**Comment by ludolphus** [comment]
Yeah I just forked the repo today, so those changes should be in. Not from #3 but I guess that's not an issue since that was just adding a compiled version of the module.

**Comment by dezinezync** [comment]
Yes, that is correct. Merged. Cheers.

**Comment by dezinezync** [comment]
Oh, before I merge it, could you please add the compiled dist so I can link it. Thanks.

**Comment by ludolphus** [comment]
it's there already :)

**Comment by dezinezync** [comment]
yes, just noticed, so merged it away. Sorry about that.

**Pull request merged**
